export const affirmations = [
  "Gratitude reminds me that what I have today was once something I prayed for.",
  "Loving myself starts with appreciating who I am right now.",
  "I am thankful for the lessons, even the difficult ones.",
  "Self-love means honoring my needs without guilt.",
  "Gratitude turns ordinary moments into meaningful ones.",
  "I thank myself for surviving what once felt impossible.",
  "Self-love is allowing myself to rest without apology.",
  "Gratitude keeps my heart calm and my mind grounded.",
  "I am enough, even while I am still growing.",
  "Being thankful helps me see beauty in simplicity.",
  "I choose to speak to myself with kindness.",
  "Gratitude teaches me to value the present moment.",
  "Loving myself means setting boundaries that protect my peace.",
  "I appreciate my body for carrying me through life.",
  "Gratitude shifts my focus from lack to abundance.",
  "I forgive myself and allow myself to heal.",
  "Self-love is patience with my own journey.",
  "I am grateful for the strength I didn’t know I had.",
  "Gratitude helps me release comparison.",
  "I honor my emotions without judging them.",
  "Loving myself means listening to my inner voice.",
  "Gratitude brings peace where worry once lived.",
  "I accept myself without needing to be perfect.",
  "I am thankful for slow growth and quiet progress.",
  "Self-love begins with self-acceptance.",
  "Gratitude reminds me that I am supported.",
  "I give myself permission to be human.",
  "I appreciate who I am becoming.",
  "Gratitude keeps me humble and hopeful.",
  "I choose gentleness with myself today.",
  "Loving myself means trusting myself again.",
  "Gratitude fills my heart with calm.",
  "I value myself beyond productivity.",
  "I am grateful for my journey, not just the destination.",
  "I am grateful for me.",
  "I am worthy of love, respect, and care.",
  "I trust myself and my decisions.",
  "I am growing at the right pace for me.",
  "I deserve peace and happiness.",
  "I honor my needs and emotions.",
  "I am proud of how far I have come.",
  "I accept myself fully and honestly.",
  "I am allowed to take up space.",
  "I am enough exactly as I am.",
  "I choose to love myself daily.",
  "Every small step forward matters.",
  "Consistency will take you where motivation can’t.",
  "You are capable of more than you think.",
  "Progress is better than perfection.",
  "Don’t quit—your effort is building something real.",
  "The work you do today shapes your tomorrow.",
  "Growth begins where comfort ends.",
  "Show up for yourself, even on hard days.",
  "Your discipline today is your freedom tomorrow.",
  "Keep going—your future self is watching."
];
